name: Build and Publish NuGet Package

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  build:
    runs-on: self-hosted
    outputs:
      Version: ${{ steps.gitversion.outputs.SemVer }}
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # fetch-depth is needed for GitVersion

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.1.1
      with:
        versionSpec: 5.x

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v1.1.1

    - name: Display GitVersion outputs
      run: |
        echo "Version: ${{ steps.gitversion.outputs.SemVer }}"
        echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"
      env:
        GITVERSION_VERSION: ${{ steps.gitversion.outputs.SemVer }}
        GITVERSION_COMMITS: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}

    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v4
    #   with:
    #     dotnet-version: 8.0.x

    - name: Build dotnet
      run: dotnet build --configuration Release

    - name: Package
      run: >
        dotnet pack SqlDbMigrator.Migrator/DbMigrator.csproj 
        -p:Version=${{ steps.gitversion.outputs.SemVer }} -c Release

    - name: Upload NuGet package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: nugetPackage
        path: ./SqlDbMigrator.Migrator/bin/Release/*.nupkg

  release:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Download NuGet package artifact
      uses: actions/download-artifact@v4
      with:
        name: nugetPackage

   # - name: Add source to nuget
   #   run: >
   #     dotnet nuget add source --username danniwezz 
   #     --password ${{ secrets.NUGET_PACKAGE_TOKEN }} 
   #     --store-password-in-clear-text 
   #     --name SqlDbMigrator 
   #     "https://nuget.pkg.github.com/danniwezz/index.json"

    - name: Publish package to GitHub packages
      run: >
        dotnet nuget push ./SqlDbMigrator.Migrator/bin/Release/SqlDbMigrator.${{ needs.build.outputs.Version }}.nupkg 
        -s https://nuget.pkg.github.com/danniwezz/index.json 
        -k ${{ secrets.NUGET_PACKAGE_TOKEN }}

    - name: Create Release in GitHub
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_PACKAGE_TOKEN }}
      with:
        tag_name: ${{ needs.build.outputs.Version }}
        release_name: SqlDbMigrator.${{ needs.build.outputs.Version }}
